server {
    listen 80;
    index index.php;
    root /var/www/;

    location ~* /(install\.php|update\.php|admin_utility\.php|check_cron_path\.php|fix_all_modules\.php|upgrade_agent_transactions\.php)$ {
        deny all;
    }

    location ~* /error_log$ {
        deny all;
    }

    location ~* /(\.env|composer\.(json|lock)|package(-lock)?\.json|yarn\.lock|docker-compose\.yml|nginx\.conf|_config\.yml)$ {
        deny all;
    }

    location ~* /.*\.(md|txt|log|sql|sqlite|db|yml|yaml|bat|bak|old|orig|save|swp|tmp)$ {
        deny all;
    }

    location ~* /.*\.php\.(bak|old|orig|save|swp|tmp|backup.*)$ {
        deny all;
    }

    location ~* /(test.*\.php|debug\.php|__error_probe\.php)$ {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php_7_4:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}
